language: node_js
node_js:
  - "8.11.1"  # Webapp
  - "8.12.0"  # Docker
cache: yarn
install:
  - npm install -g codecov
  - yarn install
cache: yarn
script:
  - yarn --version
  - yarn lint
  - yarn test
  - yarn test:coverage
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
