language: node_js
node_js:
  - "18.17.0"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install -g codecov
  - yarn install
cache: yarn
script:
  - yarn --version
  - yarn --check-cache
  - yarn lint
  - yarn test
  - yarn test:coverage
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
