language: node_js
node_js:
  - "8.4"
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
install:
  - npm install -g codecov
script:
  - yarn --version
  - yarn lint
  - yarn test
  - yarn test:coverage
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - greenkeeper-lockfile-upload
