compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

httpTimeout: 300000

npmAuditRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
