sonar.projectKey=ccd-api-gateway-web
sonar.sources=app/
sonar.tests=test/
sonar.test.inclusions=test/**/*.spec.js
sonar.exclusions=node_modules/**
sonar.coverage.exclusions=**/app-insights/**,test/**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
