nodejs:
  image: 'hmctspublic.azurecr.io/ccd/api-gateway-web:latest'
  applicationPort: 3453
  cpuLimits: 1
  environment:
    IDAM_OAUTH2_CLIENT_ID: ccd_gateway
    CORS_ORIGIN_METHODS: GET,POST,OPTIONS,PUT,DELETE
    IDAM_SERVICE_NAME: ccd_gw
    SECURE_AUTH_COOKIE_ENABLED: true

    IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-api.demo.platform.hmcts.net/oauth2/token
    IDAM_OAUTH2_LOGOUT_ENDPOINT: https://idam-api.demo.platform.hmcts.net/session/:token
    IDAM_BASE_URL: https://idam-api.demo.platform.hmcts.net
    IDAM_S2S_URL: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
    CORS_ORIGIN_WHITELIST: https://ccd-case-management-web-demo.service.core-compute-demo.internal,https://ccd-case-management-web-demo-staging.service.core-compute-demo.internal,https://ccd-case-management-web-pr-836.service.core-compute-preview.internal,http://localhost:3451,*
    PROXY_AGGREGATED: http://ccd-data-store-api-demo.service.core-compute-demo.internal
    PROXY_CASE_ACTIVITY: http://ccd-case-activity-api-demo.service.core-compute-demo.internal
    PROXY_DATA: http://ccd-data-store-api-demo.service.core-compute-demo.internal
    PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api-demo.service.core-compute-demo.internal
    PROXY_DOCUMENT_MANAGEMENT: http://dm-store-demo.service.core-compute-demo.internal
    PROXY_PAYMENTS: http://payment-api-demo.service.core-compute-demo.internal
    PROXY_PAY_BULKSCAN: http://ccpay-bulkscanning-api-demo.service.core-compute-demo.internal
    PROXY_PRINT_SERVICE: http://ccd-case-print-service-demo.service.core-compute-demo.internal
    PROXY_MV_ANNOTATIONS_API_URL: https://em-anno-demo.service.core-compute-demo.internal
  keyVaults:
    ccd-demo:
      excludeEnvironmentSuffix: true
      secrets:
        - ccd-api-gateway-oauth2-client-secret
        - ccd-gw-s2s-secret
        - postcode-info-address-lookup-token
