nodejs:
  aadIdentityName: ccd
  image: 'hmctspublic.azurecr.io/ccd/api-gateway-web:latest'
  ingressHost: 'gateway-ccd.{{ .Values.global.environment }}.platform.hmcts.net'
  applicationPort: 3453
  cpuLimits: 1
  autoscaling:
    enabled: true 
    maxReplicas: 12
  environment:
    IDAM_OAUTH2_CLIENT_ID: ccd_gateway
    CORS_ORIGIN_METHODS: GET,POST,OPTIONS,PUT,DELETE
    IDAM_SERVICE_NAME: ccd_gw
    SECURE_AUTH_COOKIE_ENABLED: true
    TIMING-ALLOW-ORIGIN: https://ccd-case-management-web-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal,https://ccd-case-management-web-{{ .Values.global.environment }}-staging.service.core-compute-{{ .Values.global.environment }}.internal
    UV_THREADPOOL_SIZE: 64
    IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/oauth2/token
    IDAM_OAUTH2_LOGOUT_ENDPOINT: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/session/:token
    IDAM_BASE_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORS_ORIGIN_WHITELIST: https://ccd-case-management-web-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal,https://ccd-case-management-web-{{ .Values.global.environment }}-staging.service.core-compute-{{ .Values.global.environment }}.internal,https://www-ccd.{{ .Values.global.environment }}.platform.hmcts.net,https://www-ccd.nonprod.platform.hmcts.net,https://www.ccd.platform.hmcts.net
    CACHE_USER_INFO_ENABLED: true
    CACHE_USER_INFO_TTL: 600
    CACHE_USER_INFO_CHECK_PERIOD: 120
    PROXY_AGGREGATED: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_CASE_ACTIVITY: http://ccd-case-activity-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_DATA: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_DOCUMENT_MANAGEMENT: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_PAYMENTS: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_PAY_BULKSCAN: http://ccpay-bulkscanning-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_PRINT_SERVICE: http://ccd-case-print-service-nodejs
    PROXY_MV_ANNOTATIONS_API_URL: http://em-anno-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PROXY_REFDATA: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    ccd:
      secrets:
        - ccd-api-gateway-oauth2-client-secret
        - postcode-info-address-lookup-token
        - microservicekey-ccd-gw
        - AppInsightsInstrumentationKey

