nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-api.demo.platform.hmcts.net/oauth2/token
    IDAM_OAUTH2_LOGOUT_ENDPOINT: https://idam-api.demo.platform.hmcts.net/session/:token
    IDAM_BASE_URL: https://idam-api.demo.platform.hmcts.net
    PROXY_MV_ANNOTATIONS_API_URL: https://em-anno-demo.service.core-compute-demo.internal
