nodejs:
  image: 'hmctspublic.azurecr.io/ccd/api-gateway-web:latest'
  applicationPort: 3453
  cpuLimits: 1
  environment:
    IDAM_OAUTH2_CLIENT_ID: ccd_gateway
    CORS_ORIGIN_METHODS: GET,POST,OPTIONS,PUT,DELETE
    IDAM_SERVICE_NAME: ccd_gw
    SECURE_AUTH_COOKIE_ENABLED: true
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
      secrets:
        - ccd-api-gateway-oauth2-client-secret
        - postcode-info-address-lookup-token
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-ccd-gw
