nodejs:
  ingressHost: ${SERVICE_FQDN}
  image: ${IMAGE_NAME}
  applicationPort: 3453
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-api.aat.platform.hmcts.net/oauth2/token
   # IDAM_OAUTH2_TOKEN_ENDPOINT: http://betaDevBccidamAppLB.reform.hmcts.net/oauth2/token
    IDAM_OAUTH2_CLIENT_ID: ccd_gateway
    #IDAM_OAUTH2_LOGOUT_ENDPOINT: http://betaDevBccidamAppLB.reform.hmcts.net/session/:token
    IDAM_OAUTH2_LOGOUT_ENDPOINT: https://idam-api.aat.platform.hmcts.net/session/:token
    CORS_ORIGIN_METHODS: GET,POST,OPTIONS,PUT,DELETE
    #IDAM_BASE_URL: http://betaDevBccidamAppLB.reform.hmcts.net
    IDAM_BASE_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_SERVICE_NAME: ccd_gw
    SECURE_AUTH_COOKIE_ENABLED: true
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
      secrets:
        - ccd-api-gateway-oauth2-client-secret
        - postcode-info-address-lookup-token
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-ccd-gw
