proxy:
  aggregated: PROXY_AGGREGATED
  data: PROXY_DATA
  definition_import: PROXY_DEFINITION_IMPORT
  document_management: PROXY_DOCUMENT_MANAGEMENT
  print_service: PROXY_PRINT_SERVICE
  case_activity: PROXY_CASE_ACTIVITY
  payments: PROXY_PAYMENTS
idam:
  base_url: IDAM_BASE_URL
  s2s_url: IDAM_S2S_URL
  service_name: IDAM_SERVICE_NAME
  oauth2:
    token_endpoint: IDAM_OAUTH2_TOKEN_ENDPOINT
    logout_endpoint: IDAM_OAUTH2_LOGOUT_ENDPOINT
    client_id: IDAM_OAUTH2_CLIENT_ID
address_lookup:
  detect_proxy: ADDRESS_LOOKUP_DETECT_PROXY
  url: ADDRESS_LOOKUP_URL
security:
  cors_origin_methods: CORS_ORIGIN_METHODS
  cors_origin_whitelist: CORS_ORIGIN_WHITELIST
  secure_auth_cookie_enabled: SECURE_AUTH_COOKIE_ENABLED
appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
secrets:
  ccd:
    ccd-api-gateway-oauth2-client-secret: IDAM_OAUTH2_CLIENT_SECRET
    postcode-info-address-lookup-token: ADDRESS_LOOKUP_TOKEN
  s2s:
    microservicekey-ccd-gw: IDAM_SERVICE_KEY
