proxy:
  aggregated: http://localhost:4452
  data: http://localhost:4452
  definition_import: http://localhost:4451
  document_management: http://localhost:4603
  print_service: https://return-case-doc.dev.ccd.reform.hmcts.net
  case_activity: http://localhost:3460
  payments: http://localhost:8080
idam:
  base_url: http://localhost:4501
  s2s_url: http://localhost:4502
  service_key: AAAAAAAAAAAAAAAC
  service_name: ccd_gw
  oauth2:
    token_endpoint: http://localhost:4501/oauth2/token
    logout_endpoint: http://localhost:4501/session/:token
    client_id: ccd_gateway
    client_secret: OOOOOOOOOOOOOOOO
address_lookup:
  detect_proxy: false
  url: https://postcodeinfo.service.justice.gov.uk/addresses?postcode=${postcode}
  token:
security:
  cors_origin_methods: "GET,POST,OPTIONS,PUT"
  cors_origin_whitelist: "http://localhost:3451,http://localhost:3452"
appInsights:
  instrumentationKey: "some-key"
  enabled: true
