proxy:
  aggregated: http://localhost:4452
  data: http://localhost:4452
  definition_import: http://localhost:4451
  document_management: http://localhost:4506
  print_service: https://return-case-doc.dev.ccd.reform.hmcts.net
  case_activity: http://localhost:3460
  payments: http://localhost:9999/payments
  pay_bulkscan: http://localhost:8888/pay-bulkscan
  refdata: http://localhost:8090/refdata
  mv_annotations: http://localhost:4623
idam:
  base_url: http://localhost:5000
  s2s_url: http://localhost:4502
  service_name: ccd_gw
  oauth2:
    token_endpoint: http://localhost:5000/oauth2/token
    logout_endpoint: http://localhost:5000/session/:token
    client_id: ccd_gateway
address_lookup:
  detect_proxy: false
  url:  https://api.ordnancesurvey.co.uk/places/v1/addresses/postcode?postcode=${postcode}&key=${key}
security:
  cors_origin_methods: "GET,POST,OPTIONS,PUT,DELETE"
  cors_origin_whitelist: "http://localhost:3451,http://localhost:3452"
  secure_auth_cookie_enabled: false
cache:
  user_info_enabled: true
  user_info_ttl: 600
  user_info_check_period: 120
appInsights:
  enabled: true
  roleName: "ccd-api-gateway"
secrets:
  ccd:
    ccd-api-gateway-oauth2-client-secret: ""
    postcode-info-address-lookup-token: AA
    microservicekey-ccd-gw: ""
    AppInsightsInstrumentationKey: ""
    
