appInsights:
  enabled: false
idam:
  base_url: http://test-idam:1234
secrets:
  ccd:
    ccd-api-gateway-oauth2-client-secret: ccd_gateway_secret
    postcode-info-address-lookup-token: AA
    microservicekey-ccd-gw: AAAAAAAAAAAAAAAC
    AppInsightsInstrumentationKey: "some-key"
