vault_section = "preprod"
idam_authentication_web_url = "https://www.preprod.ccidam.reform.hmcts.net"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://preprod-s2s-api.reform.hmcts.net:3511"
cors_origin = "https://www-ccd.nonprod.platform.hmcts.net"
document_management_url = "https://dm-store-aat.service.core-compute-aat.internal"
ccd_print_service_url = "https://return-case-doc-ccd.nonprod.platform.hmcts.net"
