vault_section = "preprod"
external_host_name = "gateway-ccd.aat.platform.hmcts.net"
idam_authentication_web_url = "https://www.preprod.ccidam.reform.hmcts.net"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
cors_origin = "https://www-ccd.nonprod.platform.hmcts.net,http://localhost:3451,*"
document_management_url = "http://dm-store-aat.service.core-compute-aat.internal"
