vault_section = "preprod"
idam_authentication_web_url = "https://www.preprod.ccidam.reform.hmcts.net"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
cors_origin = "*"
document_management_url = "http://dm-store-aat.service.core-compute-aat.internal"
