external_host_name = "gateway-ccd.demo.platform.hmcts.net"
idam_api_url = "https://idam-api.demo.platform.hmcts.net/"
cors_origin = "https://www.ccd.demo.platform.hmcts.net,https://www-ccd.demo.platform.hmcts.net"
document_management_url = "http://dm-store-demo.service.core-compute-demo.internal"
capacity = "4"
asp_name = "ccd-api-gateway-web-demo"
asp_rg = "ccd-api-gateway-web-demo"
