external_host_name = "gateway-ccd.ithc.platform.hmcts.net"
cors_origin = "*"
idam_api_url = "https://idam-api.ithc.platform.hmcts.net"
mv_annotations_api_url = ""
capacity = "4"
asp_name = "ccd-api-gateway-web-ithc"
asp_rg = "ccd-api-gateway-web-ithc"
