external_host_name = "gateway-ccd.ithc.platform.hmcts.net"
cors_origin = "https://xui-webapp-ithc.service.core-compute-ithc.internal, *"
idam_api_url = "https://idam-api.ithc.platform.hmcts.net"
mv_annotations_api_url = "https://em-anno-ithc.service.core-compute-ithc.internal"
capacity = "4"
asp_name = "ccd-api-gateway-web-ithc"
asp_rg = "ccd-api-gateway-web-ithc"
