vault_section = "preprod"
#idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
idam_api_url = "http://idam-api-idam-aat.service.core-compute-aat.internal"
#authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net"
