vault_section = "prod"
idam_authentication_web_url = "https://www.idam.reform.hmcts.net"
idam_api_url = "https://prod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://prod-s2s-api.reform.hmcts.net:3511"
cors_origin = "https://www.ccd.platform.hmcts.net,https://ccd.platform.hmcts.net"
